site_name: Metadata for Machines
nav:
    - Homework: Homework.md
    - Rules of Engagement: Rules of Engagement.md
    - Curriculum: Curriculum.md

theme: readthedocs

markdown_extensions:
    - footnotes
