site_name: Metadata for Machines
nav:
    - Preparatory Work: Preparatory Work.md
    - Rules of Engagement: Rules of Engagement.md
    - Program: Program.md

theme: readthedocs

markdown_extensions:
    - footnotes
